### ISSUE TITLE
Rebasing BibTeX::Parser on a fork of Gossen's github repository

### ISSUE THREAD

**Issue by bluebirch** [borisveytsman/BibTeXPerlLibs#1]
Dear Mr. Veytsman,

I recently begun scripting a tool using the BibTeX::Parser module by @gerhardgossen that has been so commendably improved by you. However, I ran into some problems which required further improvements of BibTeX::Parser, and I therefore created my own fork at https://github.com/bluebirch/bibtex-parser.

I now wanted to implement the improvements you made to the code, but unfortunately, I realize that you have based it on the source code that can be downloaded from CPAN. I realized this because I did exactly the same thing with your code: I just imported it from CPAN in its own branch with the intention of carefully merging all your improvements.

However, I now realize that this creates a bit of a mess, since Dist::Zilla rearranges the POD documentation in the source files, added after an `__END__` pragma which has the advantage of hiding the documentation from the Perl interpreter. Unfortunately, this means that merging your changes to my fork has become if not impossible so at least a rather time consuming and complicated task.

I do now know the best way to go from here, and I do not know if you are interested in somehow fixing this, but perhaps you, with your first hand knowledge of what changes you have made to the code, easily could fork https://github.com/gerhardgossen/bibtex-parser and re-implement those changes?

**Comment by borisveytsman** [comment]
Hi, Stefan

Thanks for your letter

I can download your version and try merging.  Plase let me know which
features of your fork you consider most important.

## 

Good luck

-Boris

Home is the place where, when you have to go there, they have to take you in.
        -- Robert Frost, "The Death of the Hired Man"

**Comment by bluebirch** [comment]
I did it the long way round, manually implementing your additions. This way, I was able to retain the POD documentation in place.

**Comment by borisveytsman** [comment]
SB> Date: Sun, 17 Jan 2016 06:19:13 -0800
SB> From: Stefan Bjrk notifications@github.com

SB> I did it the long way round, manually implementing your
SB> additions. This way, I was able to retain the POD documentation in
SB> place.

Thanks

So do you want me to merge your code now?

## 

Good luck

-Boris

Death is a spirit leaving a body, sort of like a shell leaving the nut behind.
        -- Erma Bombeck

**Comment by bluebirch** [comment]
I haven't started yet, but you can have a look at the README file at
https://github.com/bluebirch/bibtex-parser. I realized that I'm actually
aiming beyond the current scope of BibTeX::Parser.

sön 17 jan. 2016 kl 20:45 skrev Boris Veytsman notifications@github.com:

**Comment by borisveytsman** [comment]
SB> Date: Mon, 18 Jan 2016 00:40:42 -0800
SB> From: Stefan Bjrk notifications@github.com

SB> I haven't started yet, but you can have a look at the README file at
SB> https://github.com/bluebirch/bibtex-parser. I realized that I'm actually
SB> aiming beyond the current scope of BibTeX::Parser.

Actually what you put there is my goal too, since the new function
$entry->to_string.  So if you want to contribute to the main branch,
you are welcome

## 

Good luck

-Boris

The degree of civilization in a society can be judged by entering its prisons.
        -- F. Dostoyevski

**Comment by bluebirch** [comment]
In that case, I would suggest forking @gerhardgossen's repository (or mine) since that will end up in a much better documented source code (in Gossen's code the perlpod documentation is intermixed with source code, not lumped together at the end of the file - that is a result of CPAN distribution processing). That is the only reason I went through the pains of manually implementing your improvements. That, and the fact that @gerhardgossen use `Dist::Zilla`. On the other hand, I do realize the advantage of having `BibTeX::Parser` and `LaTeX::ToUnicode` in the same repository -- but that could as easily be managed with `git` submodules.

Now, I do realize this sounds like a ridiculous childish argument ("my repository is better than yours!"), but I do have some strong opinions on documentation, forking and legacy. Please bear with me. :-)

In any case, I will closely follow any updates you do to https://github.com/borisveytsman/BibTeXPerlLibs. :-)
